name: Apache Druid Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format-checker:
    runs-on: ubuntu-latest
    env:
      NULL_COMMIT: '0000000000000000000000000000000000000000'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git Clone Apache Druid
        run: git clone https://github.com/apache/druid druid

      - name: list dir
        run: ls

      - name: Change Directory to Cloned Repo
        run: cd druid

      - name: list dir inside druid
        run: ls

      # - name: Test1
      #   run: mvn clean install -DskipTests -pl extensions-core:parquet-extensions

      # - name: Test2
      #   run: mvn -pl extensions-core/parquet-extensions test -Dtest=org.apache.druid.data.input.parquet.CompatParquetReaderTest#testBinaryAsString

      # - name: Test3
      #   run: mvn -pl extensions-core/parquet-extensions edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.druid.data.input.parquet.CompatParquetReaderTest#testBinaryAsString
